import test from 'node:test';
import assert from 'node:assert/strict';
const mod=await import(process.env.GAME_MODULE??'../app/game.ts');
const {createGame,transition:step,adjacent,restoreGame,DEFAULT_CONFIG}=mod;
const start=(seed=42,c=DEFAULT_CONFIG)=>step(createGame(seed,c),{type:'start'});
const move=(g,id)=>step(g,{type:'move',id});
const fixture=()=>{const g=start();for(const r of g.rooms)if(![31,8,12].includes(r.id))r.type='empty';return g};
const type=(g,id,t)=>{const r=g.rooms.find(r=>r.id===id);r.type=t;r.cleared=false;return r};

test('all configured maps are connected, contain 27 distinct rooms, and honor counts',()=>{for(let seed=0;seed<100;seed++){const g=createGame(seed,{maxHp:4,lampMax:8,slimeCount:6,monsterCount:6,swordTarget:9});assert.equal(new Set(g.rooms.map(r=>r.id)).size,27);assert.equal(g.rooms.filter(r=>r.type==='slime').length,6);assert.equal(g.rooms.filter(r=>r.type==='monster').length,6);assert.equal(g.rooms.find(r=>r.id===8).type,'sword');assert.equal(g.rooms.find(r=>r.id===12).type,'boss');const seen=new Set([31]);for(let n=0;n<27;n++)for(const r of g.rooms)if([...seen].some(id=>adjacent(id,r.id)))seen.add(r.id);assert.equal(seen.size,27)}});
test('the same seed gives the same layout and rolls; a fresh seed gives another map',()=>{assert.deepEqual(createGame(7),createGame(7));assert.notDeepEqual(createGame(7).rooms,createGame(8).rooms)});
test('ready cannot move; distant, diagonal, missing and row-wrap moves are rejected',()=>{const ready=createGame();assert.equal(move(ready,24),ready);const g=start();for(const id of [8,23,33,-1,99])assert.equal(move(g,id),g);const h=fixture();h.pos=13;assert.equal(move(h,14),h);assert.equal(adjacent(13,14),false)});
test('moves do not mutate the preceding state, and revisiting footprints costs no light',()=>{const g=fixture(),before=JSON.stringify(g);const h=move(g,24);assert.equal(JSON.stringify(g),before);assert.equal(h.steps,1);assert.equal(h.lamp,9);assert(h.trail.includes(24));const home=move(h,31);assert.equal(home.lamp,9);assert.equal(home.phase,'explore');assert.equal(home.discovered,2)});
test('slime erases all footprints and a previously visited path costs light again',()=>{let g=fixture();type(g,17,'slime');g=move(move(g,24),17);assert.deepEqual(g.trail,[]);assert.equal(g.slimes,1);const lamp=g.lamp;g=move(g,24);assert.equal(g.lamp,lamp-1);assert.deepEqual(g.trail,[24]);g=move(g,17);assert.deepEqual(g.trail,[]);assert.equal(g.slimes,2)});
test('fleeing back into slime also erases footprints and costs exactly one light',()=>{let g=fixture();type(g,24,'slime');type(g,17,'monster');g=move(move(g,24),17);assert.equal(g.phase,'battle');const before=g.lamp;g=step(g,{type:'flee'});assert.equal(g.pos,24);assert.deepEqual(g.trail,[]);assert.equal(g.slimes,2);assert.equal(g.lamp,before-1);assert.equal(g.scene.kind,'slime')});
test('light depletion costs one health, refills, and ends the game at zero health',()=>{let g=fixture();g.lamp=1;g.hp=2;g=move(g,24);assert.equal(g.hp,1);assert.equal(g.lamp,10);g.lamp=1;g=move(g,17);assert.equal(g.phase,'lost');assert.equal(g.hp,0);assert.equal(move(g,24),g);assert.equal(step(g,{type:'potion'}),g)});
test('a visited cleared treasure cannot be farmed; exploration courage is not granted twice',()=>{let g=fixture();type(g,24,'chest');g=move(g,24);assert(g.gold>=10);assert.equal(g.courage,1);const gold=g.gold;g=move(move(g,31),24);assert.equal(g.gold,gold);assert.equal(g.courage,1);g=move(move(g,17),10);assert.equal(g.courage,2)});
test('spring heals and refills once only',()=>{let g=fixture();type(g,24,'spring');g.hp=2;g=move(g,24);assert.equal(g.hp,4);assert.equal(g.lamp,10);g=move(g,31);g.hp=2;g.lamp=3;g=move(g,24);assert.equal(g.hp,2);assert.equal(g.lamp,3)});
test('battles block movement; depleted magic and irrelevant actions have no effect',()=>{let g=fixture();type(g,24,'monster');g=move(g,24);assert.equal(g.phase,'battle');assert.equal(move(g,31),g);assert.equal(step(g,{type:'pull'}),g);g.spells=0;assert.equal(step(g,{type:'magic'}),g);assert.equal(step(g,{type:'start'}),g)});
test('guard reduces the normal counterattack, costs light, and leaves damage on a fleeing enemy',()=>{let g=fixture();type(g,24,'monster');g=move(g,24);const hp=g.hp,lamp=g.lamp;g=step(g,{type:'guard'});assert.equal(g.hp,hp);assert.equal(g.lamp,lamp-1);assert.equal(g.rooms.find(r=>r.id===24).hp,2);g=step(g,{type:'flee'});assert.equal(g.pos,31);g=move(g,24);assert.equal(g.rooms.find(r=>r.id===24).hp,2)});
test('a guarded boss still counters for one health; a defeated enemy never counters',()=>{let g=fixture();g.pos=11;g.previous=10;g.sword=true;g=move(g,12);const hp=g.hp;g=step(g,{type:'guard'});assert.equal(g.hp,hp-1);g.rooms.find(r=>r.id===12).hp=1;const before=g.hp;g=step(g,{type:'guard'});assert.equal(g.hp,before);assert.equal(g.treasure,true);assert.equal(g.gold,100);assert.equal(g.phase,'explore')});
test('boss cannot be attacked without the legendary sword',()=>{let g=fixture();g.pos=11;g.previous=10;g=move(g,12);for(const a of ['attack','guard','magic'])assert.equal(step(g,{type:a}),g);assert.equal(step(g,{type:'flee'}).pos,11)});
test('failed sword pulls grant courage and consume light; success is based on the actual roll',()=>{let g=fixture();g.pos=9;g.previous=16;g=move(g,8);g.rng=1;g.courage=0;const light=g.lamp;g=step(g,{type:'pull'});assert.equal(g.die,2);assert.equal(g.sword,false);assert.equal(g.phase,'sword');assert.equal(g.courage,1);assert.equal(g.lamp,light-1);g.courage=10;g=step(g,{type:'pull'});assert.equal(g.sword,true);assert.equal(g.phase,'explore');assert.equal(step(g,{type:'pull'}),g)});
test('leaving a sword permits exploration and reentry restores the challenge',()=>{let g=fixture();g.pos=9;g=move(g,8);g=step(g,{type:'leave'});assert.equal(g.phase,'explore');g=move(move(g,9),8);assert.equal(g.phase,'sword')});
test('potions are limited, heal at most three, never over-heal, and do not spend light',()=>{let g=fixture();assert.equal(step(g,{type:'potion'}),g);g.hp=1;const light=g.lamp;g=step(g,{type:'potion'});assert.equal(g.hp,4);assert.equal(g.potions,1);assert.equal(g.lamp,light);g=step(g,{type:'potion'});assert.equal(g.hp,6);g.hp=1;assert.equal(step(g,{type:'potion'}),g)});
test('end-to-end adventure: discover, pull, fight, loot and RETURN to win',()=>{let g=fixture();for(const id of [24,23,16,9,8])g=move(g,id);for(let i=0;i<12&&g.phase==='sword';i++){if(g.hp<3)g=step(g,{type:'potion'});g=step(g,{type:'pull'})}assert(g.sword);for(const id of [9,10,11,12])g=move(g,id);assert.equal(g.phase,'battle');g=step(step(step(g,{type:'magic'}),{type:'magic'}),{type:'guard'});assert(g.treasure);assert.notEqual(g.phase,'won');for(const id of [11,10,17,24,31])g=move(g,id);assert.equal(g.phase,'won');assert(g.hp>0);assert.equal(step(g,{type:'potion'}),g);assert.equal(move(g,24),g)});
test('saves round-trip for every phase and corrupt or impossible saves are rejected',()=>{let g=fixture();assert.deepEqual(restoreGame(JSON.stringify(g)),g);type(g,24,'monster');g=move(g,24);assert.deepEqual(restoreGame(JSON.stringify(g)),g);assert.equal(restoreGame(null),null);assert.equal(restoreGame('{nope'),null);for(const patch of [{pos:99},{hp:-1},{phase:'won'},{rooms:[]},{trail:[99]},{scene:{title:7}},{phase:'sword'},{spells:9},{die:10},{config:{...DEFAULT_CONFIG,lampMax:0}}])assert.equal(restoreGame(JSON.stringify({...g,...patch})),null)});
test('invalid settings are clamped to safe, playable limits',()=>{const g=createGame(5,{maxHp:NaN,lampMax:999,slimeCount:-4,monsterCount:999,swordTarget:2});assert.deepEqual(g.config,{maxHp:6,lampMax:16,slimeCount:1,monsterCount:6,swordTarget:5});assert.equal(g.rooms.length,27)});

function nextStep(g,target){const dist=new Map([[g.pos,0]]),paths=new Map([[g.pos,[]]]),todo=[g.pos];while(todo.length){todo.sort((a,b)=>dist.get(a)-dist.get(b));const id=todo.shift();if(id===target)return paths.get(id)[0];for(const r of g.rooms){if(!adjacent(id,r.id))continue;const risk=r.seen&&r.type==='slime'?4:1;const d=dist.get(id)+risk;if(d<(dist.get(r.id)??Infinity)){dist.set(r.id,d);paths.set(r.id,[...paths.get(id),r.id]);if(!todo.includes(r.id))todo.push(r.id)}}}throw new Error('no route')}
function play(seed,config=DEFAULT_CONFIG){let g=start(seed,config);for(let i=0;i<500&&!['won','lost'].includes(g.phase);i++){if(g.hp<=3&&g.potions){g=step(g,{type:'potion'});continue}if(g.phase==='sword'){g=step(g,{type:'pull'});continue}if(g.phase==='battle'){const r=g.rooms.find(r=>r.id===g.pos);g=step(g,{type:r.type==='boss'?(g.sword?(g.spells?'magic':'guard'):'flee'):'guard'});continue}g=move(g,nextStep(g,!g.sword?8:!g.treasure?12:31))}return g}
test('100 seeded adventures reach a terminal state; default and cozy routes remain winnable',()=>{const result={wins:0,losses:0,maxSteps:0};for(let seed=0;seed<100;seed++){const g=play(seed);assert(['won','lost'].includes(g.phase),`soft-lock at seed ${seed}`);result[g.phase==='won'?'wins':'losses']++;result.maxSteps=Math.max(result.maxSteps,g.steps);assert.deepEqual(restoreGame(JSON.stringify(g)),g)}assert(result.wins>=90,JSON.stringify(result));console.log('Seeded strategy smoke check (not a human balance study):',JSON.stringify(result));for(let seed=0;seed<20;seed++)assert.equal(play(seed,{maxHp:8,lampMax:12,slimeCount:2,monsterCount:3,swordTarget:7}).phase,'won')});
