'use client';
/* eslint-disable @next/next/no-img-element -- The same UI is exported as a fully offline HTML file. */
import {useCallback,useEffect,useRef,useState} from 'react';
import {adjacent,createGame,DEFAULT_CONFIG,LABELS,restoreGame,SAVE_KEY,transition} from './game';
import type {Action,Config,Game,RoomType} from './game';

type ModalName='rules'|'settings'|'restart'|null;
function Art({kind,small=false}:{kind:RoomType|'win'|'lose'|'hero';small?:boolean}){
 if(kind==='hero')return <div className={`hero-art ${small?'small-art':''}`} aria-hidden="true"><i/><b/><em/></div>;
 if(kind==='entrance')return <div className={`door-art ${small?'small-art':''}`} aria-hidden="true"/>;
 if(kind==='slime')return <div className={`slime-art ${small?'small-art':''}`} aria-hidden="true"><i/><b/><em/></div>;
 if(kind==='sword')return <div className={`sword-art ${small?'small-art':''}`} aria-hidden="true"><i/><b/><em/></div>;
 if(kind==='chest'||kind==='win')return <div className={`chest-art ${small?'small-art':''}`} aria-hidden="true"><i/><b/></div>;
 if(kind==='monster'||kind==='boss')return <div className={`monster-art ${kind==='boss'?'boss-art':''} ${small?'small-art':''}`} aria-hidden="true"><i/><b/><em/></div>;
 if(kind==='spring')return <div className={`spring-art ${small?'small-art':''}`} aria-hidden="true"><i/><b/></div>;
 return <div className={`boots-art ${small?'small-art':''}`} aria-hidden="true"><i/><b/></div>;
}
function Footprints(){return <span className="footprints" aria-hidden="true"><i/><b/></span>}
function Modal({name,close,children}:{name:string;close:()=>void;children:React.ReactNode}){
 const ref=useRef<HTMLDialogElement>(null);
 useEffect(()=>{const el=ref.current;el?.showModal();return()=>el?.close()},[]);
 return <dialog ref={ref} className="modal" aria-label={name} onCancel={close} onClick={e=>{if(e.target===e.currentTarget)close()}}><button className="modal-close" onClick={close} aria-label="閉じる">×</button>{children}</dialog>
}
const DIE=['','⚀','⚁','⚂','⚃','⚄','⚅'];
const PRESETS=[{name:'のんびり',desc:'たいりょく多め、スライム少なめ。',config:{maxHp:8,lampMax:12,slimeCount:2,monsterCount:3,swordTarget:7}},{name:'いつもの冒険',desc:'ほどよいドキドキと、小さな作戦。',config:DEFAULT_CONFIG},{name:'どきどき',desc:'少ない灯りで、迷宮に挑む。',config:{maxHp:4,lampMax:8,slimeCount:5,monsterCount:5,swordTarget:9}}];
export default function Home(){
 const [game,setGame]=useState<Game>(()=>createGame());const [loaded,setLoaded]=useState(false);const [modal,setModal]=useState<ModalName>(null);const [sound,setSound]=useState(false);const [draft,setDraft]=useState<Config>(DEFAULT_CONFIG);const [saveIssue,setSaveIssue]=useState(false);const [resumed,setResumed]=useState(false);
 const audio=useRef<AudioContext|null>(null);const musicTimer=useRef<number|null>(null);const musicStep=useRef(0);const eventRef=useRef<HTMLElement>(null);const boardRef=useRef<HTMLElement>(null);
 useEffect(()=>{if(!window.matchMedia("(max-width:650px)").matches)return;if(["battle","sword","won","lost"].includes(game.phase))eventRef.current?.scrollIntoView({behavior:"smooth",block:"start"})},[game.phase]);
 useEffect(()=>{let saved:Game|null=null;try{saved=restoreGame(localStorage.getItem(SAVE_KEY))}catch{/* A private browser can still play without storage. */}
 // Loading the device-local adventure after hydration preserves the server preview.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 if(saved){setGame(saved);setDraft(saved.config);setResumed(saved.phase!=='ready')}setLoaded(true);
 },[]);
 // Reflect an external storage failure once so the player knows saving is unavailable.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{if(!loaded)return;try{localStorage.setItem(SAVE_KEY,JSON.stringify(game))}catch{if(!saveIssue)setSaveIssue(true)}},[game,loaded,saveIssue]);
 const stopMusic=useCallback(()=>{if(musicTimer.current!==null){window.clearInterval(musicTimer.current);musicTimer.current=null}},[]);
 const playMusicNote=useCallback((ctx:AudioContext)=>{const notes=[220,261.63,329.63,293.66,246.94,196,246.94,293.66];const now=ctx.currentTime;const o=ctx.createOscillator(),gain=ctx.createGain(),filter=ctx.createBiquadFilter();o.type='triangle';o.frequency.setValueAtTime(notes[musicStep.current%notes.length],now);musicStep.current++;filter.type='lowpass';filter.frequency.setValueAtTime(760,now);gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(.018,now+.28);gain.gain.exponentialRampToValueAtTime(.0001,now+2.6);o.connect(filter);filter.connect(gain);gain.connect(ctx.destination);o.start(now);o.stop(now+2.65)},[]);
 const startMusic=useCallback((ctx:AudioContext)=>{stopMusic();playMusicNote(ctx);musicTimer.current=window.setInterval(()=>playMusicNote(ctx),2200)},[playMusicNote,stopMusic]);
 useEffect(()=>()=>{stopMusic();void audio.current?.close()},[stopMusic]);
 const beep=useCallback(()=>{if(!sound||!audio.current)return;const ctx=audio.current;const o=ctx.createOscillator(),gain=ctx.createGain();o.connect(gain);gain.connect(ctx.destination);o.type='sine';o.frequency.setValueAtTime(440,ctx.currentTime);o.frequency.exponentialRampToValueAtTime(660,ctx.currentTime+.07);gain.gain.setValueAtTime(.025,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.13);o.start();o.stop(ctx.currentTime+.14)},[sound]);
 const act=useCallback((action:Action)=>{setGame(g=>transition(g,action));setResumed(false);beep()},[beep]);
 useEffect(()=>{const handle=(e:KeyboardEvent)=>{if(modal||e.altKey||e.metaKey||e.ctrlKey||(e.target instanceof HTMLElement&&e.target.matches('input,select,textarea')))return;const delta:Record<string,number>={ArrowUp:-7,ArrowDown:7,ArrowLeft:-1,ArrowRight:1};if(delta[e.key]!==undefined){e.preventDefault();if(e.repeat)return;setGame(g=>transition(g,{type:'move',id:g.pos+delta[e.key]}))}};window.addEventListener('keydown',handle);return()=>window.removeEventListener('keydown',handle)},[modal]);
 const restart=(config:Config)=>{setGame(createGame(Date.now()>>>0,config));setDraft(config);setResumed(false);setModal(null)};
 const toggleSound=async()=>{if(sound){stopMusic();setSound(false);return}try{audio.current??=new AudioContext();await audio.current.resume();musicStep.current=0;startMusic(audio.current);setSound(true)}catch{return}};
 const current=game.rooms.find(r=>r.id===game.pos)!;const active=!['ready','won','lost'].includes(game.phase);const battle=game.phase==='battle';const bossBlocked=battle&&current.type==='boss'&&!game.sword;
 const attack=game.sword?3:1;const questDone=[game.sword,game.treasure,game.phase==='won'];
 const hearts=<span className="heart-icons" aria-label={`たいりょく ${game.hp} / ${game.config.maxHp}`}>{Array.from({length:game.config.maxHp},(_,i)=><span key={i} className={i<game.hp?'':'heart-empty'} aria-hidden="true">♥</span>)}</span>;
 return <main className="app-shell">
 <header className="topbar"><a className="brand" href="#" onClick={e=>{e.preventDefault();window.scrollTo({top:0,behavior:"smooth"})}} aria-label="10歩ダンジョン ホーム"><span className="brand-mark">↟</span><span>10歩ダンジョン<small>TEN-STEP DUNGEON</small></span></a><span className="edition">ひとり、気ままに。 <i/> SOLO ADVENTURE</span><div className="header-actions"><button className="icon-button sound-button" onClick={toggleSound} aria-label={sound?'音楽と効果音をオフにする':'音楽と効果音をオンにする'} title={sound?'音楽と効果音 オン':'音楽と効果音 オフ'} aria-pressed={sound}>♪<span>音楽 {sound?'ON':'OFF'}</span></button><button className="quiet-button" onClick={()=>setModal('rules')}>遊びかた <span>↗</span></button><button className="icon-button" onClick={()=>{setDraft(game.config);setModal('settings')}} aria-label="冒険の設定" title="冒険の設定">⚙</button></div></header>
 <section className="intro"><div><p className="eyebrow">A LITTLE QUEST, A LONG WAY HOME.</p><h1>帰るまでが、<span>冒険だ。</span></h1><p>足跡を残して、宝を探して。あ、スライムは踏まないで。</p></div><div className="chapter">CHAPTER 01<strong>忘れものの迷宮</strong><span>ひとり用 · 約5〜10分</span></div></section>
 <div className="game-layout"><aside className="adventurer-panel paper"><div className="panel-label">YOUR ADVENTURER <span>01</span></div><div className="portrait"><Art kind="hero"/><span className="portrait-star">✧</span>{game.sword&&<span className="equipped-badge">伝説の剣 装備中</span>}</div><h2>名もなき冒険者</h2><p className="muted">大きな夢と、ふつうの長靴。</p><div className="stat-row"><span>たいりょく</span>{hearts}</div><div className="stat-row"><span>ポケット</span><b>{game.gold} <small>G</small></b></div><div className="mini-stats"><span>攻撃 <b>{attack}</b></span><span>勇気 <b>{game.courage}</b></span></div><div className="inventory"><button disabled={!active||game.potions===0||game.hp===game.config.maxHp} onClick={()=>act({type:'potion'})} title="たいりょくを3回復。灯りを消費しません。"><span>❧</span>薬草 <b>×{game.potions}</b></button><span className="spell-count">✧ 魔法 <b>×{game.spells}</b></span></div><div className="rule-divider"/><p className="eyebrow">TODAY&apos;S QUEST</p><ol className="quest-list">{['伝説の剣を見つける','ラスボスから宝を奪う','入口まで帰ってくる'].map((q,i)=><li className={questDone[i]?'done':''} key={q}><span>{questDone[i]?'✓':i+1}</span>{q}</li>)}</ol><div className="pocket-note">忘れずに。<br/>帰り道も、冒険のうち。</div></aside>
 <section ref={boardRef} className="board-panel" aria-label="冒険の地図"><div className="mobile-stats">{hearts}<span>勇気 <b>{game.courage}</b></span><span>{game.sword?'⚔ 伝説の剣':`攻撃 ${attack}`}</span><b>{game.gold} G</b><button disabled={!active||!game.potions||game.hp===game.config.maxHp} onClick={()=>act({type:'potion'})}>薬草 ×{game.potions}</button></div><div className="board-heading"><div><span className="live-dot"/>冒険の地図 <small>THE DUNGEON</small></div><span>探索 <b>{game.discovered} / 27</b></span></div><div className={`tabletop ${game.scene.kind==='slime'?'slimed':''}`}><span className="map-corner">Ⅰ</span><span className="compass">N<br/>↑</span><div className="dungeon-grid">{Array.from({length:35},(_,id)=>{const r=game.rooms.find(r=>r.id===id);if(!r)return <span key={id} className="void-cell"/>;const isCurrent=id===game.pos,reachable=game.phase==='explore'&&adjacent(game.pos,id);const landmark=[8,12].includes(id);const marked=game.trail.includes(id);return <button key={id} className={`room ${r.seen?'revealed':'unrevealed'} ${isCurrent?'current':''} ${reachable?'reachable':''} ${r.seen?`type-${r.type}`:''} ${r.cleared?'cleared':''}`} onClick={()=>act({type:'move',id})} disabled={!reachable} aria-label={`部屋${id+1} ${r.seen?LABELS[r.type]:landmark?r.type==='sword'?'剣の気配':'ボスの気配':'未探索'}${isCurrent?' 現在地':''}${marked?' 足跡あり':''}${reachable?' 移動できる':''}`} aria-current={isCurrent?'location':undefined}><span className="room-no">{String(id+1).padStart(2,'0')}</span>{isCurrent?<Art kind="hero" small/>:r.seen?<>{r.type==='empty'||r.cleared&&['monster','chest'].includes(r.type)?<span className="stone-floor"><i/><i/><i/></span>:<Art kind={r.type} small/>}{marked&&<Footprints/>}</>:<><span className="back-mark">ダ</span>{landmark&&<span className="landmark-hint">{r.type==='sword'?'剣の気配':'ボスの気配'}</span>}</>}<small>{isCurrent?'いまここ':r.seen?LABELS[r.type]:reachable?'めくる →':''}</small>{isCurrent&&<span className="current-dot"/>}</button>})}</div><div className="map-caption"><span>↑↓←→ / タップで移動</span><span>✧ 点線のカードへ進めます</span></div></div>
 <div className={`trail-bar ${game.lamp<=3?'lamp-low':''}`}><span className="lantern" aria-hidden="true">♧</span><div><strong>灯り あと{game.lamp}歩 <span>/ {game.config.lampMax}</span></strong><div className="lamp-meter" role="meter" aria-label="灯り" aria-valuenow={game.lamp} aria-valuemin={0} aria-valuemax={game.config.lampMax}>{Array.from({length:game.config.lampMax},(_,i)=><i key={i} className={i<game.lamp?'lit':''}/>)}</div><p>{game.treasure?'お宝を持って、下の入口へ帰ろう。':game.phase==='ready'?'準備ができたら、冒険をはじめよう。':game.phase==='battle'?'出来事のカードで、戦い方を選ぼう。':game.phase==='sword'?'剣を引き抜くか、探索を続けよう。':game.scene.kind==='slime'?'スライムで足跡が消えた！ 帰りの灯りに注意。':'足跡のある部屋へは、灯りを使わず戻れます。'}</p></div><b>{game.steps}<small>歩め</small></b></div><div className="map-legend"><span><Footprints/> 足跡 {game.trail.length}</span><span>灯りが尽きると ♥ −1 で補充</span><button onClick={()=>setModal('restart')}>やり直す ↻</button></div></section>
 <aside className="encounter-column"><section className={`event-card paper ${game.phase==='won'?'victory-card':''}`} ref={eventRef} aria-label="いまの出来事"><div className="panel-label">{game.phase==='ready'?'さあ、冒険のはじまり':game.phase==='battle'?'モンスターに遭遇':game.phase==='won'?'冒険、大成功！':`第 ${game.steps} 歩のものがたり`} <span>✧</span></div><div className="event-art" key={game.scene.kind}><Art kind={game.scene.kind}/><i className="spark one">✧</i><i className="spark two">✧</i></div><div aria-live="polite" aria-atomic="true"><p className="eyebrow">{game.scene.eyebrow}</p><h2>{game.scene.title}</h2><p className="event-description">{game.scene.body}</p></div>
 {battle&&<div className="enemy-stats"><span>敵のたいりょく <b>{current.hp}</b></span><span>命中目標 <b>{current.type==='boss'?6:4}</b></span></div>}
 {game.die!==null&&<div className="die-result" key={`${game.turn}-${game.die}`} aria-label={`${game.lastRoll}の出目 ${game.die}`}><span>{DIE[game.die]}</span><div>ころころ、<b>{game.die}</b>！<small>{game.lastRoll}</small></div></div>}
 <div className="command-label"><span>いま選べること</span><small>COMMAND</small></div><div className="action-stack">{game.phase==='ready'&&<button className="primary-button" disabled={!loaded} onClick={()=>act({type:'start'})}>冒険をはじめる <span>→</span></button>}
 {game.phase==='explore'&&<button className="explore-prompt" onClick={()=>boardRef.current?.scrollIntoView({behavior:"smooth",block:"start"})}><span>✣</span><div>{game.treasure?'入口へ、帰ろう。':'次は、どこへ行こう。'}<small>点線のカードを選んで進む</small></div></button>}
 {battle&&!bossBlocked&&<><button className="primary-button" onClick={()=>act({type:'attack'})}><span>⚔ 斬りかかる<small>サイコロ＋{attack} ≥ {current.type==='boss'?6:4} で{game.sword?3:2}ダメージ</small></span><span>→</span></button><button className="secondary-button" onClick={()=>act({type:'guard'})}><span>盾で守る<small>確実に1ダメージ・反撃を1軽減</small></span><span>⛨</span></button><button className="secondary-button" disabled={!game.spells} onClick={()=>act({type:'magic'})}><span>魔法をかける <b>×{game.spells}</b><small>必ず3ダメージ・反撃なし</small></span><span>✧</span></button></>}
 {battle&&<button className="text-button" onClick={()=>act({type:'flee'})}>← ひとつ前の部屋に退く <small>灯り −1</small></button>}
 {game.phase==='sword'&&<><div className="sword-check">サイコロ ＋ 勇気 <b>{game.courage}</b><span>目標 <b>{game.config.swordTarget}</b></span></div><button className="primary-button gold-button" onClick={()=>act({type:'pull'})}>伝説の剣を引き抜く <span>↑</span></button><button className="text-button" onClick={()=>act({type:'leave'})}>もう少し、探索を続ける</button></>}
 {['won','lost'].includes(game.phase)&&<><div className="result-stats"><span>歩いた道<b>{game.steps}<small>歩</small></b></span><span>持ち帰った宝<b>{game.phase==='won'?game.gold:0}<small>G</small></b></span></div><button className="primary-button" onClick={()=>restart(game.config)}>もう一度、冒険へ <span>↻</span></button><button className="text-button" onClick={()=>{setDraft(game.config);setModal('settings')}}>冒険の難しさを変える</button></>}
 </div><p className="event-footnote">{battle?'戦う・守る・魔法は、灯りを1使います。':game.phase==='sword'?'挑戦は灯り −1。失敗しても、勇気 ＋1。':'カードをめくるたび、物語が動く。'}</p></section>
 <section className="journal" aria-label="冒険のきろく"><div className="panel-label">冒険のきろく <span>↙</span></div>{game.log.slice(0,4).map((l,i)=><p key={`${l.turn}-${i}`}><small>{String(l.turn).padStart(2,'0')}</small>{l.text}</p>)}{game.log.length>4&&<details><summary>これまでの記録を見る</summary>{game.log.slice(4).map((l,i)=><p key={i}><small>{l.turn}</small>{l.text}</p>)}</details>}</section></aside></div>
 <footer className="footer"><span>手づくりの机から、ちいさな冒険へ。</span><span>{saveIssue?'このブラウザーでは自動保存できません。':resumed?'前回の冒険を、ここから。':loaded?'この端末に自動保存しています。':'ソロ・ブラウザー版'}</span></footer>
 {modal==='rules'&&<Modal name="遊びかた" close={()=>setModal(null)}><img className="rules-art" src="/og.png" alt="10歩ダンジョン。足跡を消すスライムと、剣と宝を探す冒険者。"/><div className="modal-body"><p className="eyebrow">HOW TO PLAY</p><h2>小さな迷宮の、歩きかた。</h2><div className="rule-steps"><p><b>01　めくって、進む。</b>点線で囲まれた隣の部屋をタップ。パソコンでは矢印キーでも移動できます。北西に剣、北東にボス、入口は下の中央です。</p><p><b>02　足跡を、忘れずに。</b>足跡のない部屋へ進むと灯り −1。足跡のある部屋なら消費なし。灯りが尽きると、たいりょく −1 で灯りを補充します。標準設定は10歩ぶん。</p><p><b>03　あ、スライム。</b>踏むたび、足跡がすべて消えます。通った道にも、また灯りが必要に。場所を覚えておけば、次は避けて通れるかも。</p><p><b>04　伝説を、引き抜く。</b>剣の部屋で「サイコロ＋勇気」が目標以上なら成功。失敗は勇気 +1。新しい部屋を3つ探索するか、宝箱・戦闘でも勇気が増えます。</p><p><b>05　勝って、帰ろう。</b>剣を手に入れ、ボスを倒して宝を獲得。入口に戻ればクリア！ 戦闘は斬る・守る・魔法。薬草はたいりょくを3回復。逃げても敵のダメージは残ります。</p></div><p className="adaptation-note">写真とお話をもとにした、一人用のアレンジです。元のボードゲームの厳密なルール再現ではありません。制限時間はありません。自分のペースでどうぞ。</p><button className="primary-button" onClick={()=>setModal(null)}>わかった、冒険に戻る <span>→</span></button></div></Modal>}
 {modal==='settings'&&<Modal name="冒険の設定" close={()=>setModal(null)}><div className="modal-body"><p className="eyebrow">MAKE IT YOUR ADVENTURE</p><h2>今日は、どんな冒険に？</h2><p className="modal-description">気分に合わせて難しさを選べます。<br/>変更は、新しくはじめる冒険に反映されます。</p><div className="preset-list">{PRESETS.map(p=><button key={p.name} className={JSON.stringify(p.config)===JSON.stringify(draft)?'selected':''} onClick={()=>setDraft({...p.config})}><b>{p.name}</b><span>{p.desc}</span></button>)}</div><details className="balance-settings"><summary>自分でバランスを調整する</summary>{([{key:'maxHp',label:'たいりょく',min:3,max:10},{key:'lampMax',label:'灯りの持つ歩数',min:6,max:16},{key:'slimeCount',label:'スライムの部屋数',min:1,max:6},{key:'monsterCount',label:'モンスターの部屋数',min:2,max:6},{key:'swordTarget',label:'剣を抜く目標値',min:5,max:10}] as const).map(x=><label key={x.key}>{x.label}<input type="range" min={x.min} max={x.max} value={draft[x.key]} onChange={e=>setDraft(d=>({...d,[x.key]:Number(e.target.value)}))}/><output>{draft[x.key]}</output></label>)}</details><p className="adaptation-note">{game.phase==='ready'?'新しい迷宮で、冒険をはじめます。':'今の冒険は終了し、新しい迷宮をつくります。'}</p><button className="primary-button" onClick={()=>restart(draft)}>この設定で、新しくはじめる <span>→</span></button><button className="text-button" onClick={()=>setModal(null)}>今の冒険に戻る</button></div></Modal>}
 {modal==='restart'&&<Modal name="冒険をやり直す" close={()=>setModal(null)}><div className="modal-body"><p className="eyebrow">A FRESH START</p><h2>新しい迷宮へ、行こうか。</h2><p className="modal-description">今の冒険を終えて、カードを並べ直します。<br/>難しさは、今の設定のままです。</p><button className="primary-button" onClick={()=>restart(game.config)}>新しい冒険をはじめる <span>↻</span></button><button className="text-button" onClick={()=>setModal(null)}>今の冒険を続ける</button></div></Modal>}
 </main>
}
